"""create table reservations

Revision ID: 41b972b3c77e
Revises: 9999bb2574ce
Create Date: 2026-09-02 22:17:34.303660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b972b3c77e'
down_revision: Union[str, Sequence[str], None] = '9999bb2574ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('guest_email', sa.String(length=255), nullable=True),
    sa.Column('guest_name', sa.String(length=32), nullable=True),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='status'), nullable=False),
    sa.Column('price_paid', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_reservation_screening_row_seat_active', 'reservations', ['screening_id', 'row', 'seat'], unique=True, postgresql_where=sa.text("status != 'CANCELLED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reservation_screening_row_seat_active', table_name='reservations', postgresql_where=sa.text("status != 'CANCELLED'"))
    op.drop_table('reservations')
    # ### end Alembic commands ###
