"""add expires_at to Reservation

Revision ID: 43a0f177ffbf
Revises: 9e9e2bec64c9
Create Date: 2026-09-30 19:58:55.739123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a0f177ffbf'
down_revision: Union[str, Sequence[str], None] = '9e9e2bec64c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE reservations SET expires_at = created_at + interval '15 minutes'")
    op.alter_column('reservations', 'expires_at', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'expires_at')
    # ### end Alembic commands ###
