"""fix hall unique constraint

Revision ID: a7d7318d9509
Revises: 845394fb3c52
Create Date: 2026-08-22 17:57:03.708895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d7318d9509'
down_revision: Union[str, Sequence[str], None] = '845394fb3c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('halls_cinema_id_key'), 'halls', type_='unique')
    op.drop_constraint(op.f('halls_name_key'), 'halls', type_='unique')
    op.create_unique_constraint('uq_hall_cinema_id_name', 'halls', ['cinema_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_hall_cinema_id_name', 'halls', type_='unique')
    op.create_unique_constraint(op.f('halls_name_key'), 'halls', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('halls_cinema_id_key'), 'halls', ['cinema_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
