"""create table movies

Revision ID: ac25a3d7b94d
Revises: a7d7318d9509
Create Date: 2026-08-22 21:20:19.021574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac25a3d7b94d'
down_revision: Union[str, Sequence[str], None] = 'a7d7318d9509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Enum('ACTION', 'COMEDY', 'DRAMA', 'HORROR', 'THRILLER', 'ROMANCE', 'SCI_FI', 'FANTASY', 'ANIMATION', 'DOCUMENTARY', 'CRIME', 'ADVENTURE', 'MYSTERY', 'FAMILY', 'WAR', name='genre'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'release_date', name='uq_movie_title_release_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
