"""add user_id to payments

Revision ID: 77668c6ac945
Revises: 8d3277aff1d5
Create Date: 2026-09-17 00:06:03.919564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77668c6ac945'
down_revision: Union[str, Sequence[str], None] = '8d3277aff1d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('user_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'user_id')
    # ### end Alembic commands ###
